package com.rakesh.assignment5.employee;

/**
 * Created by Rakesh on Mar 14, 2022.
 */

public class MockApiResult {
    public String getAllEmployee() {
        return "[{\"department\":\"IT Development\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":12,\"dayOfWeek\":\"TUESDAY\",\"dayOfYear\":132,\"era\":\"CE\",\"leapYear\":false,\"month\":\"MAY\",\"monthValue\":5,\"year\":1998},\"empID\":1001,\"gender\":\"male\",\"jobLevel\":\"Junior\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"WEDNESDAY\",\"dayOfYear\":223,\"era\":\"CE\",\"leapYear\":false,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2021},\"name\":\"John\",\"salary\":35000.0},{\"department\":\"IT Development\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":20,\"dayOfWeek\":\"SUNDAY\",\"dayOfYear\":110,\"era\":\"CE\",\"leapYear\":false,\"month\":\"APRIL\",\"monthValue\":4,\"year\":1997},\"empID\":1002,\"gender\":\"male\",\"jobLevel\":\"Junior\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"TUESDAY\",\"dayOfYear\":224,\"era\":\"CE\",\"leapYear\":true,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2020},\"name\":\"Sunil\",\"salary\":35000.0},{\"department\":\"Business Analysis\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":17,\"dayOfWeek\":\"THURSDAY\",\"dayOfYear\":229,\"era\":\"CE\",\"leapYear\":false,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":1995},\"empID\":1003,\"gender\":\"male\",\"jobLevel\":\"Mid-Term\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"TUESDAY\",\"dayOfYear\":224,\"era\":\"CE\",\"leapYear\":true,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2020},\"name\":\"Rohit\",\"salary\":45000.0},{\"department\":\"Administration\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":21,\"dayOfWeek\":\"MONDAY\",\"dayOfYear\":52,\"era\":\"CE\",\"leapYear\":false,\"month\":\"FEBRUARY\",\"monthValue\":2,\"year\":1994},\"empID\":1004,\"gender\":\"male\",\"jobLevel\":\"Junior\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"WEDNESDAY\",\"dayOfYear\":223,\"era\":\"CE\",\"leapYear\":false,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2010},\"name\":\"Edwin\",\"salary\":55000.0}]";
    }

    public String getByID() {
        return "{\"department\":\"IT Development\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":12,\"dayOfWeek\":\"TUESDAY\",\"dayOfYear\":132,\"era\":\"CE\",\"leapYear\":false,\"month\":\"MAY\",\"monthValue\":5,\"year\":1998},\"empID\":1001,\"gender\":\"male\",\"jobLevel\":\"Junior\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"WEDNESDAY\",\"dayOfYear\":223,\"era\":\"CE\",\"leapYear\":false,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2021},\"name\":\"John\",\"salary\":35000.0}";
    }

    public String employeeGroup() {
        return "[{\"department\":\"Administration\",\"employeeList\":[{\"department\":\"Administration\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":21,\"dayOfWeek\":\"MONDAY\",\"dayOfYear\":52,\"era\":\"CE\",\"leapYear\":false,\"month\":\"FEBRUARY\",\"monthValue\":2,\"year\":1994},\"empID\":1004,\"gender\":\"male\",\"jobLevel\":\"Junior\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"WEDNESDAY\",\"dayOfYear\":223,\"era\":\"CE\",\"leapYear\":false,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2010},\"name\":\"Edwin\",\"salary\":55000.0}]},{\"department\":\"Business Analysis\",\"employeeList\":[{\"department\":\"Business Analysis\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":17,\"dayOfWeek\":\"THURSDAY\",\"dayOfYear\":229,\"era\":\"CE\",\"leapYear\":false,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":1995},\"empID\":1003,\"gender\":\"male\",\"jobLevel\":\"Mid-Term\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"TUESDAY\",\"dayOfYear\":224,\"era\":\"CE\",\"leapYear\":true,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2020},\"name\":\"Rohit\",\"salary\":45000.0}]},{\"department\":\"IT Development\",\"employeeList\":[{\"department\":\"IT Development\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":12,\"dayOfWeek\":\"TUESDAY\",\"dayOfYear\":132,\"era\":\"CE\",\"leapYear\":false,\"month\":\"MAY\",\"monthValue\":5,\"year\":1998},\"empID\":1001,\"gender\":\"male\",\"jobLevel\":\"Junior\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"WEDNESDAY\",\"dayOfYear\":223,\"era\":\"CE\",\"leapYear\":false,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2021},\"name\":\"John\",\"salary\":35000.0},{\"department\":\"IT Development\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":20,\"dayOfWeek\":\"SUNDAY\",\"dayOfYear\":110,\"era\":\"CE\",\"leapYear\":false,\"month\":\"APRIL\",\"monthValue\":4,\"year\":1997},\"empID\":1002,\"gender\":\"male\",\"jobLevel\":\"Junior\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"TUESDAY\",\"dayOfYear\":224,\"era\":\"CE\",\"leapYear\":true,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2020},\"name\":\"Sunil\",\"salary\":35000.0}]}]";
    }

    public String promotedEmployee() {
        return "[{\"department\":\"Administration\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":21,\"dayOfWeek\":\"MONDAY\",\"dayOfYear\":52,\"era\":\"CE\",\"leapYear\":false,\"month\":\"FEBRUARY\",\"monthValue\":2,\"year\":1994},\"empID\":1004,\"gender\":\"male\",\"jobLevel\":\"Senior\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"WEDNESDAY\",\"dayOfYear\":223,\"era\":\"CE\",\"leapYear\":false,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2010},\"name\":\"Edwin\",\"salary\":55000.0}]";
    }

    public String hikedEmployee() {
        return "[{\"department\":\"Administration\",\"dob\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":21,\"dayOfWeek\":\"MONDAY\",\"dayOfYear\":52,\"era\":\"CE\",\"leapYear\":false,\"month\":\"FEBRUARY\",\"monthValue\":2,\"year\":1994},\"empID\":1004,\"gender\":\"male\",\"jobLevel\":\"Junior\",\"joiningDate\":{\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"},\"dayOfMonth\":11,\"dayOfWeek\":\"WEDNESDAY\",\"dayOfYear\":223,\"era\":\"CE\",\"leapYear\":false,\"month\":\"AUGUST\",\"monthValue\":8,\"year\":2010},\"name\":\"Edwin\",\"salary\":55000.0}]";
    }

}
